### ISSUE TITLE
Троян в коде

### ISSUE THREAD

**Issue by halfhope** [HARDLINUX/webshell#2]
Уберите троян из кода, который отправляет данные авторизации и ссылку на файл на Ваш email. Это нарушает правила использования GitHub.

**Comment by twepl** [comment]
Это не троян, там написано сверху изменить или удалить, читай внимательно **Watching webshell!**

**Comment by halfhope** [comment]
Вы тогда хоть в ридми, а не в коде, укажите о наличии такой бесполезной и опасной модификации и email заведомо ложный подставьте, чтобы те, кто пропустил этот код не были в опасности.
